<?php

/**
 * @file
 * Hooks related to os2forms failed jobs module.
 */

use Drupal\os2forms_failed_jobs\Helper\Helper;
use Drupal\webform\WebformSubmissionInterface;

/**
 * Implements hook_views_data().
 *
 * @phpstan-return array<string, mixed>
 */
function os2forms_failed_jobs_views_data(): array {
  $data['advancedqueue']['advancedqueue_bulk_form'] = [
    'title' => 'Advanced queue operations bulk form',
    'help' => 'Add a form element that lets you run operations on multiple entries.',
    'field' => [
      'id' => 'advancedqueue_bulk_form',
    ],
  ];

  $data['advancedqueue']['retry_operation'] = [
    'title' => t('Retry operation'),
    'help' => t('Provides available operations'),
    'field' => [
      'id' => 'advancedqueue_job_retry_operation',
    ],
  ];

  $data['advancedqueue']['queue_operations'] = [
    'title' => t('Queue operations'),
    'help' => t('Provides available operations'),
    'field' => [
      'id' => 'advancedqueue_job_queue_operations',
    ],
  ];

  $data['advancedqueue']['webform_id'] = [
    'title' => t('Webform id'),
    'help' => t('Provides a related webform id if one exists in the advanced queue payload'),
    'field' => [
      'id' => 'advancedqueue_job_webform_id',
    ],
  ];

  $data['advancedqueue']['webform_label'] = [
    'title' => t('Webform label'),
    'help' => t('Provides a related webform label if one exists in the advanced queue payload'),
    'field' => [
      'id' => 'advancedqueue_job_webform_label',
    ],
  ];

  $data['advancedqueue']['webform_submission_id'] = [
    'title' => t('Webform submission id'),
    'help' => t('Provides a related webform submission id if one exists in the advanced queue payload'),
    'field' => [
      'id' => 'advancedqueue_job_webform_submission_id',
    ],
  ];

  $data['advancedqueue']['webform_submission_serial_id'] = [
    'title' => t('Webform submission serial id'),
    'help' => t('Provides a related webform submission serial id if a webform submission id exists in the advanced queue payload'),
    'field' => [
      'id' => 'advancedqueue_job_webform_submission_serial_id',
    ],
    'filter' => [
      'title' => t('Submission serial id'),
      'field' => 'id',
      'id' => 'advancedqueue_job_submission_serial',
      'allow empty' => TRUE,
    ],
  ];

  $data['advancedqueue']['advancedqueue_job_type_retry_strategy'] = [
    'title' => t('Advanced queue retry strategy description'),
    'help' => t('Provides a description of the used retry strategy'),
    'field' => [
      'id' => 'advancedqueue_job_type_retry_strategy',
    ],
  ];

  $data['advancedqueue']['advancedqueue_job_type_max_retries'] = [
    'title' => t('Advanced queue max retries for job type'),
    'help' => t('Provides the max possible retries for the job of this type'),
    'field' => [
      'id' => 'advancedqueue_job_type_max_retries',
    ],
  ];

  $data['advancedqueue']['advancedqueue_job_next_attempt'] = [
    'title' => t('Advanced queue next processsing attempt'),
    'help' => t('Provides a countdown to the next processing attempt of a job.'),
    'field' => [
      'id' => 'advancedqueue_job_next_attempt',
    ],
  ];

  $data['advancedqueue']['webform_submission_serial_exists'] = [
    'title' => t('Webform submission serial exists filter'),
    'help' => t('Provides a filter for checking if webform submission exists on a form'),
    'filter' => [
      'title' => t('Submission serial exists'),
      'field' => 'id',
      'id' => 'advancedqueue_job_submission_exists',
      'allow empty' => TRUE,
    ],
  ];

  $data['advancedqueue']['webform_submission_exists_global'] = [
    'title' => t('Webform submission exists'),
    'help' => t('Provides a filter for checking if webform submission exists across all webforms'),
    'filter' => [
      'title' => t('Submission exists'),
      'field' => 'id',
      'id' => 'advancedqueue_job_submission_exists_global',
      'allow empty' => TRUE,
    ],
  ];

  $data['advancedqueue']['webform_submission_created'] = [
    'title' => t('Webform submission created'),
    'help' => t('Provides a filter and field for submission created time'),
    'field' => [
      'id' => 'advancedqueue_job_submission_created',
    ],
    'filter' => [
      'title' => t('Submission created'),
      'field' => 'id',
      'id' => 'advancedqueue_job_submission_created',
      'allow empty' => TRUE,
    ],
  ];

  $data['advancedqueue']['webform_label_filter'] = [
    'title' => t('Webform label filter'),
    'help' => t('Provides a filter for checking if webform label matches.'),
    'filter' => [
      'title' => t('Webform label'),
      'field' => 'id',
      'id' => 'advancedqueue_job_webform_label',
      'allow empty' => TRUE,
    ],
  ];

  return $data;
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function os2forms_failed_jobs_webform_submission_delete(WebformSubmissionInterface $submission): void {
  Drupal::service(Helper::class)->cleanUp($submission);
}

/**
 * Implements hook_theme().
 *
 * @phpstan-return array<string, mixed>
 */
function os2forms_failed_jobs_theme(): array {
  return [
    'job_type_retry_strategy' => [
      'variables' => [
        'label' => NULL,
        'data' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_advanced_queue_job_type_info_alter().
 */
function os2forms_failed_jobs_advancedqueue_job_type_info_alter(array &$definitions): void {
  // Default attributes for job type definition for os2forms.
  // This will override the plugin definition defined in the module.
  $defaultAttributes = [
    'max_retries' => 5,
    'retry_delay' => 120,
    'retry_multiplier' => 5,
  ];

  // List of jobtypes that should use the os2forms default job type definition.
  $useDefault = [
    'os2forms_api_request_handler',
    'os2forms_digital_post',
    'fasit_queue',
    'os2forms_fbs_handler',
    'os2forms_forloeb',
    'os2forms_get_organized',
    'os2forms_payment',
    'os2forms_queued_email',
    'os2web_audit',
  ];

  foreach ($definitions as $key => $definition) {
    if (in_array($definition['provider'], $useDefault)) {
      $definitions[$key]['max_retries'] = $defaultAttributes['max_retries'];
      $definitions[$key]['retry_delay'] = $defaultAttributes['retry_delay'];
      $definitions[$key]['retry_multiplier'] = $defaultAttributes['retry_multiplier'];
    }
  }
}
