views.filter_value.advancedqueue_job_submission_created:
  type: views.filter_value.numeric
  label: 'Date'
  mapping:
    type:
      type: string
      label: 'Type'

views.filter.advancedqueue_job_submission_created:
  type: views.filter.numeric
  label: 'Date'
  mapping:
    type:
      type: string
      label: 'Type'